---
title: "Analysis - cone photoreceptors contribution on human physiology - iScience"
author: "Fatemeh (Mahsa) Fazlali"
date: "2024-08-01"
output: html_document
---

```{r setup, include=FALSE}
# Set options for knitting the document
knitr::opts_chunk$set(echo = TRUE)
```

#Clean environment
```{r, include=FALSE}
# Clear the environment to avoid any leftover variables or data from previous sessions.
rm(list=ls()) 

# Close any open graphic devices to prevent issues with plotting.
graphics.off()  

```

#Install and load required packages
```{r}
# Install 'pacman', a package manager that helps manage other R packages.
# Load necessary libraries for the analysis, including packages for visualization, GLM, and Bayesian analysis.


if (!requireNamespace("pacman", quietly = TRUE)) {
  install.packages("pacman")
}
pacman::p_load(
  # Data manipulation and plotting
  ggplot2, dplyr, tidyverse,
  cowplot, ggpubr, gridExtra, grid,
  # Modeling and Bayesian analysis (not used in this script)
  rstanarm, brms, bayestestR, BayesFactor,
  # Utility
  pROC, ggridges, ggdist, zoo, see, bayesplot, ggeffects, BayesPostEst
)

```

# Import dataset (use relative paths for portability)
```{r}
# Import the melatonin and subjective alertness (KSS) data.
# Make sure the file paths are correct and use relative paths if possible for portability.
#Mel_KSS_TP<- 
#  read.csv("data/Melatonin_KSS_data.csv")

# Import AUC (Area Under the Curve) and average KSS data.
AUC_KSS<- 
  read.csv("data/AUC_AvgKSS_data_id.csv")

```


#--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------Plotting----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


-------------------------------------------------------------------------------------------------------------
#Functions for plotting
```{r}
# Define custom colors for different light conditions
# 'BL', 'BG', etc., refer to specific light conditions. please check the manuscript 
custom_colors <- c(
  "BL" = "gray30", 
  "BG" = "gray70", 
  "S" = "dodgerblue", 
  "ML" = "green3", 
  "SML" = "magenta"
  )


# Create a function for generating consistent plots across different dataset
# Parameters:
#   - data: The data to be plotted
#   - y_var: The dependent variable (AUC or KSS)
#   - y_label: The y-axis label
#   - scale_y_breaks: The y-axis tick marks
#   - scale_y_limits: The y-axis range
#   - legend_s: The position of the legend

create_plot <- function(data, y_var, y_label, scale_y_breaks, scale_y_limits, legend_s) {
  ggplot(data, aes(x = Condition, y = !!sym(y_var), fill= Condition)) +
      scale_fill_manual(values = custom_colors, name = " ") +
  geom_violin(trim = FALSE, alpha = 0.5, adjust = 0.5) +  # Violin plot to show the distribution of data.
  geom_boxplot(width = 0.2, alpha = 0.7, position = position_dodge(width = 0.9), outlier.shape = NA) +  # Boxplot to show summary statistics.
  geom_jitter(position = position_nudge(y = 0.2) , size = 0.7, alpha = 1) +  # Jittered points to show individual data points.
  geom_line(aes(group = id), linetype = "dashed",position = position_nudge(y = 0.2), color = "black", alpha = 0.5) +  # Dashed lines connecting points for each participant.
  labs(title = "", x = "", y = y_label, color = "Light condition") +  # Set axis labels.
  theme(
    panel.background = element_rect(fill = "white", colour = "white"),  # White background for the plot.
    plot.background = element_rect(fill = "white", colour = NA),  # White background for the plot area.
    axis.line.x = element_line(color = "black", size = 0.5),  # Add a black line for the x-axis.
    axis.line.y = element_line(color = "black", size = 0.5),
    legend.position = legend_s,  # Control legend position using the argument passed to the function.
    axis.title.x = element_text(size = 12),  # Set size for x-axis label.
    axis.title.y = element_text(size = 12),  # Set size for y-axis label.
    axis.text.x = element_text(size = 11),  # Set size for x-axis tick labels.
    axis.text.y = element_text(size = 11),  # Set size for y-axis tick labels.
    legend.text = element_text(size = 11),  # Set size for legend text.
    legend.key.size = unit(1, "lines")  # Set size for the legend key.
  ) +
  scale_y_continuous(breaks = scale_y_breaks, limits = scale_y_limits)  # Define y-axis breaks and limits.
}

```

#Data subsets for AUC analysis
```{r}
# Subset the AUC_KSS data for specific conditions: removing S-cone, M-L, and S+M+L conditions.
AUC_KSS_BLBG <- subset(AUC_KSS, Condition != "S" & Condition != "ML" & Condition != "SML")
AUC_KSS_BLBG$Condition <- as.character(AUC_KSS_BLBG$Condition)
AUC_KSS_BLBG$Condition <- factor(AUC_KSS_BLBG$Condition, levels = c("BL", "BG"))  # Re-level the factors to control the plotting order.
AUC_KSS_BLBG <- AUC_KSS_BLBG %>%
  arrange(id, Condition)

AUC_KSS_BLBG <- AUC_KSS_BLBG[!is.na(AUC_KSS_BLBG$Condition), ]

# Group participants by their light condition combinations.
S_ML_SML <- AUC_KSS %>%
  group_by(id) %>%
  summarize(Conditions = paste(sort(unique(Condition)), collapse = ","))

# Filter participants for S, ML, and SML conditions.
S <- S_ML_SML %>%
  filter(Conditions == "BG,BL,S")
ML <- S_ML_SML %>%
  filter(Conditions == "BG,BL,ML")
SML <- S_ML_SML %>%
  filter(Conditions == "BG,BL,SML")

# Further subset the data based on light condition combinations.
AUC_KSS_S <- AUC_KSS %>% filter(id %in% S$id)
AUC_KSS_S$Condition <- factor(AUC_KSS_S$Condition, levels = c("BL", "BG", "S"))
AUC_KSS_S <- subset(AUC_KSS_S, Condition != "BL")

AUC_KSS_ML <- AUC_KSS %>% filter(id %in% ML$id)
AUC_KSS_ML$Condition <- factor(AUC_KSS_ML$Condition, levels = c("BL", "BG", "ML"))
AUC_KSS_ML <- subset(AUC_KSS_ML, Condition != "BL")

AUC_KSS_SML <- AUC_KSS %>% filter(id %in% SML$id)
AUC_KSS_SML$Condition <- factor(AUC_KSS_SML$Condition, levels = c("BL", "BG", "SML"))
AUC_KSS_SML <- subset(AUC_KSS_SML, Condition != "BL")

```

#Plotting melatonin AUC figure
```{r}
#general
AUCALL <- create_plot(AUC_KSS_BLBG, "AUC", "",  
              scale_y_breaks = seq(0, 200, 50), scale_y_limits = c(-10, 200),"")
AUCS <- create_plot(AUC_KSS_S, "AUC", "", 
             scale_y_breaks = seq(0, 200, 50), scale_y_limits = c(-10, 200),"")
AUCML <- create_plot(AUC_KSS_ML, "AUC", "", 
             scale_y_breaks = seq(0, 200, 50), scale_y_limits = c(-10, 200),"")
AUCSML <- create_plot(AUC_KSS_SML, "AUC", "",  
              scale_y_breaks = seq(0, 200, 50), scale_y_limits = c(-10, 200),"")


#winter
AUCALL_wnt <- create_plot(subset(AUC_KSS_BLBG, Season == "Winter"), "AUC", "", 
             scale_y_breaks = seq(0, 200, 50), scale_y_limits = c(-10, 200),"")
AUCS_wnt <- create_plot(subset(AUC_KSS_S, Season == "Winter"), "AUC", "", 
             scale_y_breaks = seq(0, 200, 50), scale_y_limits = c(-10, 200),"")
AUCML_wnt <- create_plot(subset(AUC_KSS_ML, Season == "Winter"), "AUC", "", 
             scale_y_breaks = seq(0, 200, 50), scale_y_limits = c(-10, 200),"")
AUCSML_wnt <- create_plot(subset(AUC_KSS_SML, Season == "Winter"), "AUC", "", 
             scale_y_breaks = seq(0, 200, 50), scale_y_limits = c(-10, 200),"")


#summer  
AUCALL_smr <- create_plot(subset(AUC_KSS_BLBG, Season == "Summer"), "AUC", "", 
             scale_y_breaks = seq(0, 200, 50), scale_y_limits = c(-10, 200),"")
AUCS_smr <- create_plot(subset(AUC_KSS_S, Season == "Summer"), "AUC", "", 
             scale_y_breaks = seq(0, 200, 50), scale_y_limits = c(-10, 200),"")
AUCML_smr <- create_plot(subset(AUC_KSS_ML, Season == "Summer"), "AUC", "", 
             scale_y_breaks = seq(0, 200, 50), scale_y_limits = c(-10, 200),"")
AUCSML_smr <- create_plot(subset(AUC_KSS_SML, Season == "Summer"), "AUC", "", 
             scale_y_breaks = seq(0, 200, 50), scale_y_limits = c(-10, 200),"")

# Create a temporary plot with a visible legend for extraction
temp_plot1 <- create_plot(subset(AUC_KSS_BLBG, Season == "Summer"), "AUC", "",  
                         scale_y_breaks = seq(0, 200, 50), 
                         scale_y_limits = c(-10, 200), 
                         legend_s = "bottom")

# Extract the legend from this temporary plot
legend_plot1 <- as_ggplot(get_legend(temp_plot1))

# Create a temporary plot with a visible legend for extraction
temp_plot2 <- create_plot(AUC_KSS_S, "AUC", "",  
                         scale_y_breaks = seq(0, 200, 50), 
                         scale_y_limits = c(-10, 200), 
                         legend_s = "bottom")

# Extract the legend from this temporary plot
legend_plot2 <- as_ggplot(get_legend(temp_plot2))

# Create a temporary plot with a visible legend for extraction
temp_plot3 <- create_plot(AUC_KSS_ML, "AUC", "",  
                         scale_y_breaks = seq(0, 200, 50), 
                         scale_y_limits = c(-10, 200), 
                         legend_s = "bottom")

# Extract the legend from this temporary plot
legend_plot3 <- as_ggplot(get_legend(temp_plot3))

# Create a temporary plot with a visible legend for extraction
temp_plot4 <- create_plot(AUC_KSS_SML, "AUC", "",  
                         scale_y_breaks = seq(0, 200, 50), 
                         scale_y_limits = c(-10, 200), 
                         legend_s = "bottom")

# Extract the legend from this temporary plot
legend_plot4 <- as_ggplot(get_legend(temp_plot4))

legend_plots <- arrangeGrob(
  legend_plot1, legend_plot2, legend_plot3, legend_plot4,
  ncol = 4,
  heights = c(6, 0.5)  # Adjust legend height ratio
)

legend_plots_right <- grobTree(legend_plots, vp = viewport(x = 0.03, just = "left"))  # x = 0.8 pushes it right


# Create row titles as grobs
row_title_all_season <- textGrob("All Season", gp = gpar(fontsize = 14, fontface = "bold"))
row_title_winter <- textGrob("Winter", gp = gpar(fontsize = 14, fontface = "bold"))
row_title_summer <- textGrob("Summer", gp = gpar(fontsize = 14, fontface = "bold"))


# Create labeled groups for each row using ggarrange() which accepts a labels argument.
row_all <- ggarrange(AUCALL, AUCS, AUCML, AUCSML, ncol = 4, labels = c("a", "b", "c", "d"),
  font.label = list(size = 11, face = "bold", color = "black"))
row_winter <- ggarrange(AUCALL_wnt, AUCS_wnt, AUCML_wnt, AUCSML_wnt, ncol = 4, labels = c("e", "f", "g", "h"),
  font.label = list(size = 11, face = "bold", color = "black"))
row_summer <- ggarrange(AUCALL_smr, AUCS_smr, AUCML_smr, AUCSML_smr, ncol = 4, labels = c("i", "j", "k", "l"),
  font.label = list(size = 11, face = "bold", color = "black"))

# Arrange the rows with their corresponding row titles.
figure_layout  <- arrangeGrob(
  row_title_all_season, 
  row_all, 
  row_title_winter,
  row_winter, 
  row_title_summer, 
  row_summer, 
  ncol = 1,
  heights = c(0.1, 1, 0.1, 1, 0.1, 1) # Adjust the title heights as needed
)

# Combine figure and legend into a single plot layout
final_plot <- arrangeGrob(
  figure_layout, legend_plots_right,
  ncol = 1,
  heights = c(6, 0.3)  # Adjust legend height ratio
)

# If you wish to print or save the combined plot:
grid.draw(final_plot)
# ggsave(file = "path/to/your/combined_plot.jpg", AllAUCSML, width = 12, height = 18, units = "in", dpi = 300)

# Adjust the position of the labels using vjust and hjust
final_plot <- annotate_figure(final_plot,
                              left = text_grob("Melatonin AUC [pg/mL/h]", size = 18, rot = 90, 
                                               vjust = 0.2, hjust = 0.5),  # Adjust vertical/horizontal justifications
                              bottom = text_grob("Light Condition", size = 18, 
                                                 vjust = 1.5, hjust = 0.5)) 

# If you need extra space between the plot and the edges, you can use plot.margin
final_plot <- final_plot + theme(plot.margin = unit(c(1,1,1,1), "cm"))  

# Save the updated figure
ggsave(file = "AUC.jpg",
       plot = final_plot,
       width = 7.3, 
       height = 11, 
       units = "in", 
       dpi = 300)

```

#Plotting average KSS figure
```{r}
#general
KSSALL <- create_plot(AUC_KSS_BLBG, "Avg_KSS", "",  
              scale_y_breaks = seq(1, 9, 1), scale_y_limits = c(1, 10),"")
AVEKSSS <- create_plot(AUC_KSS_S, "Avg_KSS", "", 
             scale_y_breaks = seq(1, 9, 1), scale_y_limits = c(1, 10),"")
AVEKSSML <- create_plot(AUC_KSS_ML, "Avg_KSS", "", 
             scale_y_breaks = seq(1, 9, 1), scale_y_limits = c(1, 10),"")
AVEKSSSML <- create_plot(AUC_KSS_SML, "Avg_KSS", "",  
             scale_y_breaks = seq(1, 9, 1), scale_y_limits = c(1, 10),"")



#winter
KSSALL_wnt <- create_plot(subset(AUC_KSS_BLBG, Season == "Winter"), "Avg_KSS", "",
             scale_y_breaks = seq(1, 9, 1), scale_y_limits = c(1, 10),"")
AVEKSSS_wnt <- create_plot(subset(AUC_KSS_S, Season == "Winter"),"Avg_KSS", "", 
             scale_y_breaks = seq(1, 9, 1), scale_y_limits = c(1, 10),"")
AVEKSSML_wnt <- create_plot(subset(AUC_KSS_ML, Season == "Winter"), "Avg_KSS", "", 
             scale_y_breaks = seq(1, 9, 1), scale_y_limits = c(1, 10),"")
AVEKSSSML_wnt <- create_plot(subset(AUC_KSS_SML, Season == "Winter"), "Avg_KSS", "", 
             scale_y_breaks = seq(1, 9, 1), scale_y_limits = c(1, 10),"")



#summer
KSSALL_smr <- create_plot(subset(AUC_KSS_BLBG, Season == "Summer"), "Avg_KSS", "",
             scale_y_breaks = seq(1, 9, 1), scale_y_limits = c(1, 10),"")
AVEKSSS_smr <- create_plot(subset(AUC_KSS_S, Season == "Summer"), "Avg_KSS", "", 
             scale_y_breaks = seq(1, 9, 1), scale_y_limits = c(1, 10),"")
AVEKSSML_smr <- create_plot(subset(AUC_KSS_ML, Season == "Summer"), "Avg_KSS", "",  
             scale_y_breaks = seq(1, 9, 1), scale_y_limits = c(1, 10),"")
AVEKSSSML_smr <- create_plot(subset(AUC_KSS_SML, Season == "Summer"), "Avg_KSS", "", 
             scale_y_breaks = seq(1, 9, 1), scale_y_limits = c(1, 10),"")


# Create labeled groups for each row using ggarrange()
row_all <- ggarrange(KSSALL, AVEKSSS, AVEKSSML, AVEKSSSML, 
                     ncol = 4, labels = c("a", "b", "c", "d"),
  font.label = list(size = 11, face = "bold", color = "black"))
row_winter <- ggarrange(KSSALL_wnt, AVEKSSS_wnt, AVEKSSML_wnt, AVEKSSSML_wnt, 
                        ncol = 4, labels = c("e", "f", "g", "h"),
  font.label = list(size = 11, face = "bold", color = "black"))
row_summer <- ggarrange(KSSALL_smr, AVEKSSS_smr, AVEKSSML_smr, AVEKSSSML_smr, 
                        ncol = 4, labels = c("i", "j", "k", "l"),
  font.label = list(size = 11, face = "bold", color = "black"))

# Arrange the rows with their corresponding row titles.
figure_layout <- arrangeGrob(
  row_title_all_season, 
  row_all, 
  row_title_winter,
  row_winter, 
  row_title_summer, 
  row_summer, 
  ncol = 1,
  heights = c(0.1, 1, 0.1, 1, 0.1, 1) # Ensures uniform height for all rows
)

# Combine figure and legend into a single plot layout
final_plot <- arrangeGrob(
  figure_layout, legend_plots_right,
  ncol = 1,
  heights = c(6, 0.3)  # Adjusts legend height ratio
)

# If you wish to print or save the combined plot:
grid.draw(final_plot)

# Adjust the position of the labels using vjust and hjust
final_plot <- annotate_figure(final_plot,
                              left = text_grob("Subjective Alertness (KSS)", size = 18, rot = 90, 
                                               vjust = 0.2, hjust = 0.5),  
                              bottom = text_grob("Light Condition", size = 18, 
                                                 vjust = 1.5, hjust = 0.5)) 

# Add margin adjustments
final_plot <- final_plot + theme(plot.margin = unit(c(1,1,1,1), "cm"))  

# Save the updated figure
ggsave(file = "KSS.jpg",
       plot = final_plot,
       width = 7.3, 
       height = 11, 
       units = "in", 
       dpi = 300)

```




#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------Statistical-Analysis-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

---------------------------------
#Bayesian Analysis
```{r}
#AUC analysis
#null hypothesis for AUC
f01 <- "AUC ~ Season + (1|id)"
#full hypothesis for AUC
f1 <- "AUC ~ Condition * Season + (1|id)"

#-------------------------------------
#KSS analysis 
#null hypothesis for KSS
f02 <- "Avg_KSS ~ Season + (1|id)"
#full hypothesis for KSS
f2 <- "Avg_KSS ~ Condition * Season + (1|id)"

```

#Default prior normal (0,1)
```{r}
# Define the function
perform_analysis <- function(data, formula_null, formula_alt, chains = 4, iter = 20000) {
  
  # Fit the null model
  model_null <- stan_glmer(
    formula = formula_null,
    data = data,
    prior = normal(),
    prior_intercept = normal(),
    chains = chains,
    iter = iter,
    diagnostic_file = "diag01.csv"
    )
  
  # Summary of the null model
  print(summary(model_null))
  
  # Fit the alternative model
  model_alt <- stan_glmer(
    formula = formula_alt,
    data = data,
    prior = normal(),
    prior_intercept = normal(),
    chains = chains,
    iter = iter,
    diagnostic_file = "diag2.csv" 
    )
  
  # Summary of the alternative model
  print(summary(model_alt))
  
  # Extract posterior samples
  posterior_samples <- as.data.frame(model_alt)
  
  # Compute the 95% credible intervals
  CI95 <- posterior_interval(model_alt, prob = 0.95)
  
  # Compute Bayes factor
  bf <- bayesfactor_models(model_null, model_alt)
  
  # Compute Effective Sample Size (ESS)
  ess_values <- effective_sample(model_alt)
  
  # Compute Probability of Direction (pd)
  pd_values <- pd(model_alt)
  
  print(summary(model_null))
  print(summary(model_alt))
  print(bf)
  print(ess_values)
  print(pd_values)
  # Return the models and Bayes factor
  return(list(model_null = model_null, model_alt = model_alt, bayes_factor = bf, posterior_samples = posterior_samples, CI95 = CI95, ESS = ess_values, pd = pd_values))
}

```


#All participants BG&BL 
```{r}
#AUC
#-------------------------------------------------
AUC_KSS_BLBG$Condition <- factor(AUC_KSS_BLBG$Condition, levels = c("BG", "BL"))  # Re-level the factors to control the plotting order.
AUC_KSS_BLBG <- AUC_KSS_BLBG %>%
  arrange(id, Condition)

#-----------------------------------------------------
# Perform analyses and Extract posterior samples
result1 <- perform_analysis(AUC_KSS_BLBG, f01, f1)
CI95_1 <- result1$CI95
posterior_samples1 <- result1$posterior_samples
ESS_1 <- result1$ESS
pd_1 <- result1$pd

#Avg_KSS 
#------------------------------------------------------
result2 <- perform_analysis(AUC_KSS_BLBG, f02, f2)
CI95_2 <- result2$CI95
posterior_samples2 <- result2$posterior_samples
ESS_2 <- result2$ESS
pd_2 <- result2$pd


```

#s_cone group
```{r}
#AUC
#-------------------------------------------------
# Perform analyses
result3 <- perform_analysis(AUC_KSS_S, f01, f1)
CI95_3 <- result3$CI95
posterior_samples3 <- result3$posterior_samples
ESS_3 <- result3$ESS
pd_3 <- result3$pd

#Avg_KSS 
result4 <- perform_analysis(AUC_KSS_S, f02, f2)
CI95_4 <- result4$CI95
posterior_samples4 <- result4$posterior_samples
ESS_4 <- result4$ESS
pd_4 <- result4$pd

```


#M-L group
```{r}
#AUC
#-------------------------------------------------
# Perform analyses
result5 <- perform_analysis(AUC_KSS_ML, f01, f1)
CI95_5 <- result5$CI95
posterior_samples5 <- result5$posterior_samples
ESS_5 <- result5$ESS
pd_5 <- result5$pd
#Avg_KSS 
#------------------------------------------------------
result6 <- perform_analysis(AUC_KSS_ML, f02, f2)
CI95_6 <- result6$CI95
posterior_samples6 <- result6$posterior_samples
ESS_6 <- result6$ESS
pd_6 <- result6$pd
#Extract posterior samples

```


#S+M+L group
```{r}
#AUC
#-------------------------------------------------
# Perform analyses
result7 <- perform_analysis(AUC_KSS_SML, f01, f1)
CI95_7 <- result7$CI95
posterior_samples7 <- result7$posterior_samples
ESS_7 <- result7$ESS
pd_7 <- result7$pd

result8 <- perform_analysis(AUC_KSS_SML, f02, f2)
CI95_8 <- result8$CI95
posterior_samples8 <- result8$posterior_samples
ESS_8 <- result8$ESS
pd_8 <- result8$pd

```

-----------------------------------------------------------------------------------------------------------------------------
#posterior plots
```{r}
# Plot the posterior distributions to visually compare effect magnitudes
library(bayesplot)

# Rename parameters for better readability
param_names1 <- c(
  "ConditionBL" = "BL light",
  "SeasonWinter" = "Season",
  "ConditionBL:SeasonWinter" = " BL light * Season")
  
param_names3 <- c(
  "ConditionS" = "S-cone light",
  "SeasonWinter" = "Season",
  "ConditionS:SeasonWinter" = "S-cone light * Season")

param_names5 <- c(
  "ConditionML" = "M-L light",
  "SeasonWinter" = "Season",
  "ConditionML:SeasonWinter" = "M-L light * Season")

param_names7 <- c( 
  "ConditionSML" = "S+M+L light",
  "SeasonWinter" = "Season",
  "ConditionSML:SeasonWinter" = "S+M+L light * Season")
  

library(ggpubr)

# Function to create a posterior plot for a given posterior sample dataset
create_posterior_plot <- function(posterior_samples, title, param_names) {
  mcmc_areas(
    posterior_samples,
    pars = names(param_names),  # Use renamed parameters
    prob = 0.95
  ) +  
    scale_y_discrete(labels = param_names) +
    ggtitle(title) +
    xlab("")   # Apply minimal theme
}

# AUC
plot_posterior1 <- create_posterior_plot(posterior_samples1, "Dim vs. Background light", param_names1)
plot_posterior3 <- create_posterior_plot(posterior_samples3, "Background vs. S-cone light", param_names3 )
plot_posterior5 <- create_posterior_plot(posterior_samples5, "Background vs. M-L light", param_names5)
plot_posterior7 <- create_posterior_plot(posterior_samples7, "Background vs. S+M+L light", param_names7)

#KSS
plot_posterior2 <- create_posterior_plot(posterior_samples2, "Dim vs. Background light", param_names1)
plot_posterior4 <- create_posterior_plot(posterior_samples4, "Background vs. S-cone light", param_names3 )
plot_posterior6 <- create_posterior_plot(posterior_samples6, "Background vs. M-L light", param_names5)
plot_posterior8 <- create_posterior_plot(posterior_samples8, "Background vs. S+M+L light", param_names7)

# Combine all four plots into a 2x2 grid
combined_posterior_plots <- ggarrange(
  plot_posterior1, plot_posterior3, plot_posterior5, plot_posterior7,
  ncol = 2, nrow = 2,
  labels = c("a", "b", "c", "d")  # Label each plot
)

# Print the final combined figure
print(combined_posterior_plots)

# Save the combined plot
ggsave(file = "Posterior_Distributions_AUC.jpg",
       plot = combined_posterior_plots,
       width = 12, 
       height = 10, 
       units = "in", 
       dpi = 300)


# Combine all four plots into a 2x2 grid
combined_posterior_plots <- ggarrange(
  plot_posterior2, plot_posterior4, plot_posterior6, plot_posterior8,
  ncol = 2, nrow = 2,
  labels = c("a", "b", "c", "d")  # Label each plot
)

# Print the final combined figure
print(combined_posterior_plots)

# Save the combined plot
ggsave(file = "Posterior_Distributions_KSS.jpg",
       plot = combined_posterior_plots,
       width = 12, 
       height = 10, 
       units = "in", 
       dpi = 300)

```
